[workspace]
members = [
    "sql_tool_macros",
    "sql_tool_core"
]
exclude = [
    "examples/gen_fields_demo",
    "examples/gen_select_demo",
    "examples/gen_values_demo"
    # 其他要排除的包
]
resolver = "2"